services:
  backend:
    container_name: aida-backend
    build:
      context: ./backend
    env_file:
      - ./backend/${ENV_FILE}
    volumes:
      - ./backend:/app
      - ./storage:/storage
      - /app/node_modules
    ports:
      - 6100:3000
      - 9229:9229
    command: pnpm run start:dev
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - backend

  frontend:
    container_name: aida-frontend
    build:
      context: ./frontend
    env_file:
      - ./frontend/${ENV_FILE}
    volumes:
      - ./frontend:/app
      - ./storage:/storage
      - /app/node_modules
    ports:
      - 5173:5173
      - 9228:9228
    command: pnpm run start:dev
    restart: unless-stopped
    networks:
      - backend

  compute:
    image: aida-compute
    container_name: aida-compute
    build:
      context: ./compute
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8002:8000"
    volumes:
      - ./compute:/app
      - ./storage:/storage
    env_file:
      - ./compute/${ENV_FILE}
    restart: unless-stopped
    networks:
      - backend

  worker:
    image: aida-worker
    container_name: aida-worker
    build:
      context: ./compute
    command: celery -A src.tasks.celery_app worker --loglevel=info
    volumes:
      - ./compute:/app
      - ./storage:/storage
    env_file:
      - ./compute/${ENV_FILE}
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:7
    container_name: aida-redis
    ports:
      - "6380:6379"
    restart: unless-stopped
    networks:
      - backend

  rabbitmq:
    image: rabbitmq:4-management
    container_name: aida-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: unless-stopped
    networks:
      - backend

  postgres:
    container_name: aida-postgres
    image: postgres:16
    env_file:
      - ./backend/${ENV_FILE}
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  pgdata:
  rabbitmq:

networks:
  backend:
