services:
  api:
    container_name: aida-api
    build:
      context: ./api
    env_file:
      - ./api/.development.env
    volumes:
      - ./api:/app
      - /app/node_modules
    ports:
      - 6100:3000
      - 9229:9229
    command: pnpm run start:dev
    depends_on:
      - postgres
    restart: unless-stopped

  front:
    container_name: aida-front
    build:
      context: ./front
    env_file:
      - ./front/.development.env
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 5173:5173
      - 9228:9228
    command: pnpm run start:dev
    restart: unless-stopped

  worker_api:
    image: aida-worker_api
    container_name: aida-worker_api
    build:
      context: ./worker
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8002:8000"
    volumes:
      - ./worker:/app
      - ./storage:/storage
    env_file:
      - ./worker/.env.local
    restart: unless-stopped

  worker:
    image: aida-celery
    container_name: aida-celery
    build:
      context: ./worker
    command: celery -A src.tasks.celery_app worker --loglevel=info
    volumes:
      - ./worker:/app
      - ./storage:/storage
    env_file:
      - ./worker/.env.local
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: aida-redis
    ports:
      - "6380:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:4-management
    container_name: aida-rabbitmq

    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - rabbitmq:/var/lib/rabbitmq

    restart: unless-stopped

  postgres:
    container_name: aida-postgres
    image: postgres:16
    env_file:
      - ./api/.development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
  rabbitmq:
